apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
  namespace: attendance
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
        - name: attendance-service
          image: nnitheshreddy/attendance-tracker:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: attendance-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: attendance-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
