apiVersion: v1
kind: ConfigMap
metadata:
  name: attendance-config
  namespace: attendance
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DB_HOST: "attendance-db"
  DB_PORT: "5432"
  DB_NAME: "attendancedb"
  DB_USER: "postgres"
