apiVersion: v1
kind: Secret
metadata:
  name: attendance-db-secret
  namespace: attendance
type: Opaque
stringData:
  DB_PASSWORD: "<your-password>"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "<your-password>"
  POSTGRES_DB: "attendancedb"
